version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-tests:
    executor:
      mane: node/default
    steps:
      - checkout
      - node/with-cache: 
          steps:
            -run: 
              name: "Say hello"
              command: "mp install"
workflows:
  build-and-tests:
    jobs:
      - build-and-tests
