version: 2.1

orbs:
  node: circleci/node@18.16

jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.16'
      - run: npm install
      - run: npm test
workflows:
  test_my_app:
    jobs:
      - install-node-example


